from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from app.domain.tags.models import Tag


class TagRepository(Protocol):
    async def add(self, tag: Tag) -> Tag: ...

    async def get_by_id(self, tag_id: UUID) -> Tag | None: ...

    async def get_by_slug(self, slug: str) -> Tag | None: ...

    async def list(self) -> list[Tag]: ...

    async def list_by_ids(self, tag_ids: tuple[UUID, ...]) -> Sequence[Tag]: ...

    async def save(self, tag: Tag) -> Tag: ...

    async def delete(self, tag_id: UUID) -> None: ...
