from typing import Protocol
from uuid import UUID

from app.domain.users.entities import User


class UserRepository(Protocol):
    async def add(self, user: User) -> User: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_login(self, login: str) -> User | None: ...
    async def list(self, *, offset: int, limit: int) -> list[User]: ...
    async def save(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class AccessTokenService(Protocol):
    def create(self, user_id: UUID) -> str: ...
    def decode(self, token: str) -> UUID: ...


class VerificationNotifier(Protocol):
    async def send_email_verification(self, email: str, token: str) -> None: ...
    async def send_phone_verification(self, phone: str, token: str) -> None: ...
